alter_onetable_stmt ::=
	'ALTER' 'TABLE' table_name 'AUDIT' 'SET' 'READ' 'WRITE'
	| 'ALTER' 'TABLE' table_name 'AUDIT' 'SET' 'OFF'
	| 'ALTER' 'TABLE' 'IF' 'EXISTS' table_name 'AUDIT' 'SET' 'READ' 'WRITE'
	| 'ALTER' 'TABLE' 'IF' 'EXISTS' table_name 'AUDIT' 'SET' 'OFF'
