insert_stmt ::=
	( ( 'WITH' ( ( common_table_expr ) ( ( ',' common_table_expr ) )* ) | 'WITH' 'RECURSIVE' ( ( common_table_expr ) ( ( ',' common_table_expr ) )* ) ) |  ) 'INSERT' 'INTO' ( table_name_opt_idx | table_name_opt_idx 'AS' table_alias_name ) ( select_stmt | 'OVERRIDING' 'SYSTEM' 'VALUE' select_stmt | 'OVERRIDING' 'USER' 'VALUE' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' 'OVERRIDING' 'SYSTEM' 'VALUE' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' 'OVERRIDING' 'USER' 'VALUE' select_stmt | 'DEFAULT' 'VALUES' ) ( 'RETURNING' ( ( target_elem ) ( ( ',' target_elem ) )* ) | 'RETURNING' 'NOTHING' |  )
	| ( ( 'WITH' ( ( common_table_expr ) ( ( ',' common_table_expr ) )* ) | 'WITH' 'RECURSIVE' ( ( common_table_expr ) ( ( ',' common_table_expr ) )* ) ) |  ) 'INSERT' 'INTO' ( table_name_opt_idx | table_name_opt_idx 'AS' table_alias_name ) ( select_stmt | 'OVERRIDING' 'SYSTEM' 'VALUE' select_stmt | 'OVERRIDING' 'USER' 'VALUE' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' 'OVERRIDING' 'SYSTEM' 'VALUE' select_stmt | '(' ( ( ( column_name ) ) ( ( ',' ( column_name ) ) )* ) ')' 'OVERRIDING' 'USER' 'VALUE' select_stmt | 'DEFAULT' 'VALUES' ) on_conflict ( 'RETURNING' ( ( target_elem ) ( ( ',' target_elem ) )* ) | 'RETURNING' 'NOTHING' |  )
